---
title: "15q_dup"
author: "Brandon"
date: "4/8/2021"
output: html_document
---
#load working directory and library
```{r setup, include=FALSE}
#setwd("C:/Users/khuub/One Drive/OneDrive/Desktop/Projects/projects/Autism_edgeR/")
library(edgeR)
```

#load data
```{r}
counts <- read.csv("15q_dup_fpkm.csv")
m = as.matrix(counts)
g <- c('Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case')
```

#create DGE List
```{r}
d <- DGEList(counts = m, group = g)
```

#calcNormFactors
```{r}
d <- calcNormFactors(d)
```

#load covariates
```{r}
co <- read.csv('15qdup_pc1.csv',header=FALSE)
```

#common dispersion
```{r}
d <- estimateDisp(d,design=co)
```

#exact test
```{r}
de.com <- exactTest(d,pair=c("Case","Control"))
topTags(de.com)
```
#output pvalue
```{r}
pval <- de.com$table$PValue
write.csv(pval,"15qdup_pval_with_covar.csv")
```

```{r}
write.csv(de.com$table, "15qdup_covar_full_table.csv")
```