---
title: "15q_dup"
author: "Brandon"
date: "4/8/2021"
output: html_document
---
#load working directory and library
```{r setup, include=FALSE}
setwd("C:/Users/khuub/One Drive/OneDrive/Desktop/Projects/projects/Autism_edgeR/")
library(edgeR)
```

#load data
```{r}
counts <- read.csv("16p11_fpkm.csv")
m = as.matrix(counts)
g <- c('Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Control','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','Case','case')
```

#create DGE List
```{r}
d <- DGEList(counts = m, group = g)
```

#calcNormFactors
```{r}
d <- calcNormFactors(d)
```

#common dispersion
```{r}
d <- estimateCommonDisp(d,pair=c("Case","Control"))
```

#exact test
```{r}
de.com <- exactTest(d)
topTags(de.com)
```

```{r}
write.csv(de.com$table$pvalue, "16p11_pval.csv")
```
#output pvalue
```{r}
pval <- de.com$table$PValue
write.csv(pval,"16p11_pval_without_covar.csv")
```
