---
title: "Full File - Mito EQTL"
author: "Brandon"
date: "3/3/2021"
output: html_document
---
#Import Librarys
```{r setup, include=FALSE}
library(MatrixEQTL)
```

##Files
```{r cars}
allele = read.csv ="allele.csv";
count_expression= "count_expression.csv";
count_expression_edit = "count_expression_no_zero.csv";
count_expression_log_norm = "count_expression_log_norm.csv";
count_expression_log_norm = "read_count_log2_normalization.csv";
count_expression_standard_norm = "count_expression_standard_norm.csv";
count_expression_minmax = "count_expression_minmax_norm.csv"
count_expression_normalizer = "count_expression_normalizer.csv"
count_expression_robust = "count_expression_robust.csv"

covariates = "mito_covariates.csv"
```

##Settings
```{r}
#settings for engine
useModel = modelLINEAR

covariates = covariates;

output_file_name = tempfile();

pvOutputThreshold = 1e-2;

errorCovariance = numeric();

cisDist = 1e6;
```

#Load data
```{r}
#Genotype
snps = SlicedData$new();
snps$fileDelimiter = ",";
snps$fileOmitCharacters = "NA";
snps$fileSkipRows = 1;
snps$fileSkipColumns = 1;
snps$fileSliceSize = 2000;
snps$LoadFile(allele);

#Expression - Log Standardized
gene_log = SlicedData$new();
gene_log$fileDelimiter = ",";
gene_log$fileOmitCharacters = "NA";
gene_log$fileSkipRows = 1;
gene_log$fileSkipColumns = 1;
gene_log$fileSliceSize = 2000;
gene_log$LoadFile("count_expression_log_norm.csv");

#Expression - SK Learn StandardScaler
gene_stan = SlicedData$new();
gene_stan$fileDelimiter = ",";
gene_stan$fileOmitCharacters = "NA";
gene_stan$fileSkipRows = 1;
gene_stan$fileSkipColumns = 1;
gene_stan$fileSliceSize = 2000;
gene_stan$LoadFile("count_expression_standard_norm.csv");

#Expression - SK Learn MinMax
gene_minmax = SlicedData$new();
gene_minmax$fileDelimiter = ",";
gene_minmax$fileOmitCharacters = "NA";
gene_minmax$fileSkipRows = 1;
gene_minmax$fileSkipColumns = 1;
gene_minmax$fileSliceSize = 2000;
gene_minmax$LoadFile(count_expression_minmax);

#Expression - SK Learn Normalizer
gene_norm = SlicedData$new();
gene_norm$fileDelimiter = ",";
gene_norm$fileOmitCharacters = "NA";
gene_norm$fileSkipRows = 1;
gene_norm$fileSkipColumns = 1;
gene_norm$fileSliceSize = 2000;
gene_norm$LoadFile(count_expression_normalizer);

#Expression - SK Learn Normalizer
gene_rob = SlicedData$new();
gene_rob$fileDelimiter = ",";
gene_rob$fileOmitCharacters = "NA";
gene_rob$fileSkipRows = 1;
gene_rob$fileSkipColumns = 1;
gene_rob$fileSliceSize = 2000;
gene_rob$LoadFile(count_expression_robust);

#covariates
cvrt = SlicedData$new();
cvrt$fileDelimiter = ",";      
cvrt$fileOmitCharacters = "NA"; 
cvrt$fileSkipRows = 1;          
cvrt$fileSkipColumns = 1;       
if(length(covariates)>0) {
  cvrt$LoadFile(covariates);}
```

##Analysis
```{r}
#log normalized and covariates data
me_log = Matrix_eQTL_engine(
  snps = snps,
  gene = gene_log,
  cvrt = cvrt,
  output_file_name = output_file_name,
  pvOutputThreshold = pvOutputThreshold,
  useModel = useModel,
  errorCovariance = errorCovariance,
  verbose = TRUE,
  pvalue.hist = TRUE,
  min.pv.by.genesnp = FALSE,
  noFDRsaveMemory = FALSE
);

unlink(output_file_name)

#log normalized and covariates data
me_log_qq = Matrix_eQTL_engine(
  snps = snps,
  gene = gene_log,
  cvrt = cvrt,
  output_file_name = output_file_name,
  pvOutputThreshold = pvOutputThreshold,
  useModel = useModel,
  errorCovariance = errorCovariance,
  verbose = TRUE,
  pvalue.hist = "qqplot",
  min.pv.by.genesnp = FALSE,
  noFDRsaveMemory = FALSE
);

unlink(output_file_name)
```

```{r}
#standardized and covariates data
me_stan = Matrix_eQTL_engine(
  snps = snps,
  gene = gene_stan,
  cvrt = cvrt,
  output_file_name = output_file_name,
  pvOutputThreshold = pvOutputThreshold,
  useModel = useModel,
  errorCovariance = errorCovariance,
  verbose = TRUE,
  pvalue.hist = TRUE,
  min.pv.by.genesnp = FALSE,
  noFDRsaveMemory = FALSE
);

unlink(output_file_name)

#standardized and covariates data
me_stan_qq = Matrix_eQTL_engine(
  snps = snps,
  gene = gene_stan,
  cvrt = cvrt,
  output_file_name = output_file_name,
  pvOutputThreshold = pvOutputThreshold,
  useModel = useModel,
  errorCovariance = errorCovariance,
  verbose = TRUE,
  pvalue.hist = "qqplot",
  min.pv.by.genesnp = FALSE,
  noFDRsaveMemory = FALSE
);

unlink(output_file_name)
```

```{r}
#minmax and covariates data
me_minmax= Matrix_eQTL_engine(
  snps = snps,
  gene = gene_minmax,
  cvrt = cvrt,
  output_file_name = output_file_name,
  pvOutputThreshold = pvOutputThreshold,
  useModel = useModel,
  errorCovariance = errorCovariance,
  verbose = TRUE,
  pvalue.hist = TRUE,
  min.pv.by.genesnp = FALSE,
  noFDRsaveMemory = FALSE
);

unlink(output_file_name)

#minmax and covariates data
me_minmax_qq = Matrix_eQTL_engine(
  snps = snps,
  gene = gene_minmax,
  cvrt = cvrt,
  output_file_name = output_file_name,
  pvOutputThreshold = pvOutputThreshold,
  useModel = useModel,
  errorCovariance = errorCovariance,
  verbose = TRUE,
  pvalue.hist = "qqplot",
  min.pv.by.genesnp = FALSE,
  noFDRsaveMemory = FALSE
);

unlink(output_file_name)
```

```{r}
#standardized and covariates data
me_norm = Matrix_eQTL_engine(
  snps = snps,
  gene = gene_norm,
  cvrt = cvrt,
  output_file_name = output_file_name,
  pvOutputThreshold = pvOutputThreshold,
  useModel = useModel,
  errorCovariance = errorCovariance,
  verbose = TRUE,
  pvalue.hist = TRUE,
  min.pv.by.genesnp = FALSE,
  noFDRsaveMemory = FALSE
);

unlink(output_file_name)

#standardized and covariates data
me_norm_qq = Matrix_eQTL_engine(
  snps = snps,
  gene = gene_norm,
  cvrt = cvrt,
  output_file_name = output_file_name,
  pvOutputThreshold = pvOutputThreshold,
  useModel = useModel,
  errorCovariance = errorCovariance,
  verbose = TRUE,
  pvalue.hist = "qqplot",
  min.pv.by.genesnp = FALSE,
  noFDRsaveMemory = FALSE
);

unlink(output_file_name)
```

```{r}
#standardized and covariates data
me_rob = Matrix_eQTL_engine(
  snps = snps,
  gene = gene_rob,
  cvrt = cvrt,
  output_file_name = output_file_name,
  pvOutputThreshold = pvOutputThreshold,
  useModel = useModel,
  errorCovariance = errorCovariance,
  verbose = TRUE,
  pvalue.hist = TRUE,
  min.pv.by.genesnp = FALSE,
  noFDRsaveMemory = FALSE
);

unlink(output_file_name)

#standardized and covariates data
me_rob_qq = Matrix_eQTL_engine(
  snps = snps,
  gene = gene_rob,
  cvrt = cvrt,
  output_file_name = output_file_name,
  pvOutputThreshold = pvOutputThreshold,
  useModel = useModel,
  errorCovariance = errorCovariance,
  verbose = TRUE,
  pvalue.hist = "qqplot",
  min.pv.by.genesnp = FALSE,
  noFDRsaveMemory = FALSE
);

unlink(output_file_name)
```

##Results
```{r}
#log normalized data
cat('Analysis done in: ', me_log$time.in.sec, ' seconds', '\n');
cat('Detected eQTLs:', '\n');
show(me_log$all$eqtls)
```

```{r}
#standard noramlized data
cat('Analysis done in: ', me_stan$time.in.sec, ' seconds', '\n');
cat('Detected eQTLs:', '\n');
show(me_stan$all$eqtls)
```

```{r}
#standard noramlized data
cat('Analysis done in: ', me_minmax$time.in.sec, ' seconds', '\n');
cat('Detected eQTLs:', '\n');
show(me_minmax$all$eqtls)
```

```{r}
#standard noramlized data
cat('Analysis done in: ', me_norm$time.in.sec, ' seconds', '\n');
cat('Detected eQTLs:', '\n');
show(me_norm$all$eqtls)
```

```{r}
#standard noramlized data
cat('Analysis done in: ', me_rob$time.in.sec, ' seconds', '\n');
cat('Detected eQTLs:', '\n');
show(me_rob$all$eqtls)
```

##plot
```{r}
#log normlized data
plot(me_log)
plot(me_log_qq)
```

```{r}
#standard normalized data
plot(me_stan)
plot(me_stan_qq)
```

```{r}
#standard normalized data
plot(me_minmax)
plot(me_minmax_qq)
```

```{r}
#standard normalized data
plot(me_norm)
plot(me_norm_qq)
```

```{r}
#sk learn robust scaler data
plot(me_rob)
plot(me_rob_qq)
```